/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EventX;

import javax.swing.SwingUtilities;

public class App {

    public static void main(String[] args)
     {
         System.out.println("Running \n");
         
         SwingUtilities.invokeLater(() -> {
             DisplayManager ob=new DisplayManager();
             ob.getLogin().load_page();
        });  
        
     }
}
